title = "RevolucionArte"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "es-sv"
theme = 'ananke'
resourceDir = "../resources"
contentDir = "content/"


DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "near-black"
  body_classes = "helvetica bg-near-white"
  author = ""
  favicon = "/featured/iconLogo.png"
  site_logo = "/featured/iconLogo.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  recent_posts_number = 3
  custom_css = ['custom.css']

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/revolucionarte.pna/"
